version: '3'                # version of docker compose
services:                   # هنا ببدا اعرف اللحاجات اللى هستخدمها زى مثلا لو هستخدم داتابيز دى كدة هتكون serviceوهكذا
  node-app:                 # هنا انا عندى service واحدة بيتاعت البرنامج وسميتها node-app
    build:
      context: .
      # args:
      #   - NODE_ENV=develpoment   # علشان اقدر ابعت arges when i build to docker file
      target: development
    volumes:
      - ./src:/app/src:ro    # بمعنى ابسط انا بدل ما افضل اكتب كوماند كتير علشان اعمل build and run for all conatinersهنا بعرف كل واحدة محتاجة اى
    environment:
      - NODE_ENV=development
    command: npm run start-dev
