version: '3'                # version of docker compose
services:                   # هنا ببدا اعرف اللحاجات اللى هستخدمها زى مثلا لو هستخدم داتابيز دى كدة هتكون serviceوهكذا
  node-app:                 # هنا انا عندى service واحدة بيتاعت البرنامج وسميتها node-app
    build:
      context: .
      # args:
      #   - NODE_ENV=production     #  علشان اقدر ابعت arges when i build to docker file
      target: production
    environment:
      - NODE_ENV=production
    command: npm start
